# Generated by Django 2.0.5 on 2020-07-04 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='author',
            new_name='author_id',
        ),
    ]
