# Generated by Django 3.0.8 on 2020-07-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20200704_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='author_id',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
